all:
	#mipsel-linux-gcc main.c -o show_bin -lSDL_image -lSDL -lSDL_ttf -I/home/steward/Github/rs97_toolchain/os/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL
	gcc main.c -g -o show_bin -lSDL_image -lSDL -lSDL_ttf -I/usr/include/SDL
clean:
	rm -rf show_bin
